name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: cdkservicehostmodule/go.mod

      - name: Build wrapper module
        working-directory: cdkservicehostmodule
        run: go build ./...
